# Generated by Django 2.1.1 on 2018-09-14 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Batch'),
            preserve_default=False,
        ),
    ]
