# Generated by Django 2.1.1 on 2018-09-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentinfo_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='batch',
            field=models.ForeignKey(on_delete=None, to='student.Batch'),
        ),
    ]
