# Generated by Django 2.1.1 on 2018-09-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180914_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.Batch'),
        ),
    ]
