# Generated by Django 2.1.1 on 2018-09-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20180914_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
